### ISSUE TITLE
Cannot use hubot

### ISSUE THREAD

**Issue by shuta13** [frdmn/docker-rocketchat#4]
# question：cannot use hubot
`[shuta13@shuta13-hoge] /var/docker/Rocket.Chat$ docker-compose up -d hubot`
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid top-level property "hubot". Valid top-level sections for this Compose file are: version, services, networks, volumes, and extensions starting with "x-".

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**Comment by frdmn** [comment]
Can I see the `docker-compose.yml` file you're trying to use?

**Comment by shuta13** [comment]
`docker-compose.yml` file : 
```
version: '2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:0.74.1
    restart: unless-stopped
    command: /bin/sh -c 'INSTANCE_IP=$$(hostname -i) node main.js'
    mem_limit: 4G
    volumes:
     - ./data/uploads:/app/uploads
     - /tmp:/tmp
    environment:
     - PORT=3000
     - ROOT_URL=http://${ROCKETCHAT_HOST}
     - MONGO_URL=mongodb://mongo:27017/rocketchat
     - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: ${ROCKETCHAT_HOST}"
    depends_on:
      - mongo

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
    volumes:
      - ./data/db:/data/db
      - ./data/backups:/dump

  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    depends_on:
      - mongo

  traefik:
    image: traefik:1.6.4
    restart: unless-stopped
    command: traefik --web --docker --defaultentrypoints=http --entryPoints='Name:http Address::3000'
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

hubot:
  image: rocketchat/hubot-rocketchat:1.0.8
  restart: unless-stopped
  environment:
    - MONGODB_URL=mongodb://mongo:27017/hubot-brain
    - ROCKETCHAT_URL=rocketchat:3000
    - ROCKETCHAT_ROOM=${ROCKETCHAT_ROOM}
    - ROCKETCHAT_USER=${ROCKETCHAT_USER}
    - ROCKETCHAT_PASSWORD=${ROCKETCHAT_PASSWORD}
    - BOT_NAME=${BOT_NAME}
    - EXTERNAL_SCRIPTS=${EXTERNAL_SCRIPTS}
    - TZ=${TZ}
  links:
    - rocketchat:rocketchat
  volumes:
    - ./data/hubotscripts:/home/hubot/scripts
  ports:
    - 3001:8081
```
I just removed `#` signs and rewrited `.env` file

**Comment by frdmn** [comment]
Try to indent the `hubot` block one level more so it looks like this:

```
  hubot:
    image: rocketchat/hubot-rocketchat:1.0.8
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://mongo:27017/hubot-brain
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ROOM=${ROCKETCHAT_ROOM}
      - ROCKETCHAT_USER=${ROCKETCHAT_USER}
      - ROCKETCHAT_PASSWORD=${ROCKETCHAT_PASSWORD}
      - BOT_NAME=${BOT_NAME}
      - EXTERNAL_SCRIPTS=${EXTERNAL_SCRIPTS}
      - TZ=${TZ}
    links:
      - rocketchat:rocketchat
    volumes:
      - ./data/hubotscripts:/home/hubot/scripts
    ports:
      - 3001:8081
```

Make sure it is _within_ the `services` block not next to it.
